### ISSUE TITLE
Can't download routing files for hike and bike: This site can’t be reached

### ISSUE THREAD

**Issue by razvanbogza** [develar/gh-routing-data#2]
Hi, I was trying several times to download the routing files for Romania using the link provided on this page https://graphhopper.develar.org/#maps ,but I only get this message: This site can’t be reached. How can I download the needed archive? Thank you!

**Comment by develar** [comment]
Server rebooted :) Works now.

**Comment by razvanbogza** [comment]
Thank you very much!
